package xxgam.oracle.apps.xbol.tm.freight.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DownloadVORowImpl extends OAViewRowImpl
{
  public static final int FILEID = 0;
  public static final int FILENAME = 1;
  public static final int FILEDATA = 2;

  /**This is the default constructor (do not remove)
   */
  public DownloadVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute FileId
   */
  public Number getFileId()
  {
    return (Number) getAttributeInternal(FILEID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute FileId
   */
  public void setFileId(Number value)
  {
    setAttributeInternal(FILEID, value);
  }

  /**Gets the attribute value for the calculated attribute FileName
   */
  public String getFileName()
  {
    return (String) getAttributeInternal(FILENAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute FileName
   */
  public void setFileName(String value)
  {
    setAttributeInternal(FILENAME, value);
  }

  /**Gets the attribute value for the calculated attribute FileData
   */
  public BlobDomain getFileData()
  {
    return (BlobDomain) getAttributeInternal(FILEDATA);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute FileData
   */
  public void setFileData(BlobDomain value)
  {
    setAttributeInternal(FILEDATA, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case FILEID:
      return getFileId();
    case FILENAME:
      return getFileName();
    case FILEDATA:
      return getFileData();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
}
