package xxgam.oracle.apps.xbol.tm.freight.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OperationUserVORowImpl extends OAViewRowImpl
{
  public static final int USERID = 0;
  public static final int ORGANIZATION = 1;
  public static final int LOCATIONCODE = 2;
  public static final int AREACODE = 3;

  /**This is the default constructor (do not remove)
   */
  public OperationUserVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute UserId
   */
  public Number getUserId()
  {
    return (Number) getAttributeInternal(USERID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute UserId
   */
  public void setUserId(Number value)
  {
    setAttributeInternal(USERID, value);
  }

  /**Gets the attribute value for the calculated attribute Organization
   */
  public String getOrganization()
  {
    return (String) getAttributeInternal(ORGANIZATION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Organization
   */
  public void setOrganization(String value)
  {
    setAttributeInternal(ORGANIZATION, value);
  }

  /**Gets the attribute value for the calculated attribute LocationCode
   */
  public String getLocationCode()
  {
    return (String) getAttributeInternal(LOCATIONCODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute LocationCode
   */
  public void setLocationCode(String value)
  {
    setAttributeInternal(LOCATIONCODE, value);
  }

  /**Gets the attribute value for the calculated attribute AreaCode
   */
  public String getAreaCode()
  {
    return (String) getAttributeInternal(AREACODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute AreaCode
   */
  public void setAreaCode(String value)
  {
    setAttributeInternal(AREACODE, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case USERID:
      return getUserId();
    case ORGANIZATION:
      return getOrganization();
    case LOCATIONCODE:
      return getLocationCode();
    case AREACODE:
      return getAreaCode();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
}
