package xxgam.oracle.apps.xbol.tm.freight.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxgam.oracle.apps.xbol.tm.freight.schema.RequestEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestVORowImpl extends OAViewRowImpl {
    public static final int IDREQUEST = 0;
    public static final int IDSTATUS = 1;
    public static final int STATUS = 2;
    public static final int OPERATINGUNIT = 3;
    public static final int OUDESCRIPTION = 4;
    public static final int IDAREA = 5;
    public static final int ADESCRIPTION = 6;
    public static final int USERNAME = 7;
    public static final int IDPRIORITY = 8;
    public static final int PRIORITYCODE = 9;
    public static final int ACTIVATIONDATE = 10;
    public static final int ACTIVATIONTIME = 11;
    public static final int MATERIALDATE = 12;
    public static final int MATERIALTIME = 13;
    public static final int IDSHIPPER = 14;
    public static final int SHIPPER = 15;
    public static final int IDRECEIVER = 16;
    public static final int RECEIVER = 17;
    public static final int DOCUMENT1 = 18;
    public static final int DOCUMENT2 = 19;
    public static final int DOCUMENT3 = 20;
    public static final int ATTRIBUTE1 = 21;
    public static final int ATTRIBUTE2 = 22;
    public static final int ATTRIBUTE3 = 23;
    public static final int ATTRIBUTE4 = 24;
    public static final int ATTRIBUTE5 = 25;
    public static final int ATTRIBUTE6 = 26;
    public static final int ATTRIBUTE7 = 27;
    public static final int ATTRIBUTE8 = 28;
    public static final int ATTRIBUTE9 = 29;
    public static final int ATTRIBUTE10 = 30;
    public static final int LASTUPDATEDATE = 31;
    public static final int LASTUPDATEDBY = 32;
    public static final int CREATIONDATE = 33;
    public static final int CREATEDBY = 34;
    public static final int LASTUPDATELOGIN = 35;
    public static final int COMMENTS = 36;
    public static final int MULTIPLEDELIVERIES = 37;
    public static final int DESTINATION = 38;
    public static final int IDDESTINATION = 39;
    public static final int IDORIGIN = 40;
    public static final int IDZONE = 41;
    public static final int ORIGIN = 42;
    public static final int ZONEDESC = 43;
    public static final int FREIGHTENABLED = 44;
    public static final int ISRECORDENABLED = 45;

    /**This is the default constructor (do not remove)
     */
  public RequestVORowImpl()
  {
  }

  /**Gets RequestEO entity object.
   */
  public RequestEOImpl getRequestEO()
  {
    return (RequestEOImpl)getEntity(0);
  }

  /**Gets the attribute value for ID_REQUEST using the alias name IdRequest
   */
  public Number getIdRequest()
  {
    return (Number) getAttributeInternal(IDREQUEST);
  }

  /**Sets <code>value</code> as attribute value for ID_REQUEST using the alias name IdRequest
   */
  public void setIdRequest(Number value)
  {
    setAttributeInternal(IDREQUEST, value);
  }

  /**Gets the attribute value for ID_STATUS using the alias name IdStatus
   */
  public Number getIdStatus()
  {
    return (Number) getAttributeInternal(IDSTATUS);
  }

  /**Sets <code>value</code> as attribute value for ID_STATUS using the alias name IdStatus
   */
  public void setIdStatus(Number value)
  {
    setAttributeInternal(IDSTATUS, value);
  }

  /**Gets the attribute value for STATUS using the alias name Status
   */
  public String getStatus()
  {
    return (String) getAttributeInternal(STATUS);
  }

  /**Sets <code>value</code> as attribute value for STATUS using the alias name Status
   */
  public void setStatus(String value)
  {
    setAttributeInternal(STATUS, value);
  }

  /**Gets the attribute value for OPERATING_UNIT using the alias name OperatingUnit
   */
  public String getOperatingUnit()
  {
    return (String) getAttributeInternal(OPERATINGUNIT);
  }

  /**Sets <code>value</code> as attribute value for OPERATING_UNIT using the alias name OperatingUnit
   */
  public void setOperatingUnit(String value)
  {
    setAttributeInternal(OPERATINGUNIT, value);
  }

  /**Gets the attribute value for OU_DESCRIPTION using the alias name OuDescription
   */
  public String getOuDescription()
  {
    return (String) getAttributeInternal(OUDESCRIPTION);
  }

  /**Sets <code>value</code> as attribute value for OU_DESCRIPTION using the alias name OuDescription
   */
  public void setOuDescription(String value)
  {
    setAttributeInternal(OUDESCRIPTION, value);
  }

  /**Gets the attribute value for ID_AREA using the alias name IdArea
   */
  public Number getIdArea()
  {
    return (Number) getAttributeInternal(IDAREA);
  }

  /**Sets <code>value</code> as attribute value for ID_AREA using the alias name IdArea
   */
  public void setIdArea(Number value)
  {
    setAttributeInternal(IDAREA, value);
  }

  /**Gets the attribute value for A_DESCRIPTION using the alias name ADescription
   */
  public String getADescription()
  {
    return (String) getAttributeInternal(ADESCRIPTION);
  }

  /**Sets <code>value</code> as attribute value for A_DESCRIPTION using the alias name ADescription
   */
  public void setADescription(String value)
  {
    setAttributeInternal(ADESCRIPTION, value);
  }

  /**Gets the attribute value for USER_NAME using the alias name UserName
   */
  public String getUserName()
  {
    return (String) getAttributeInternal(USERNAME);
  }

  /**Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName
   */
  public void setUserName(String value)
  {
    setAttributeInternal(USERNAME, value);
  }

  /**Gets the attribute value for ID_PRIORITY using the alias name IdPriority
   */
  public Number getIdPriority()
  {
    return (Number) getAttributeInternal(IDPRIORITY);
  }

  /**Sets <code>value</code> as attribute value for ID_PRIORITY using the alias name IdPriority
   */
  public void setIdPriority(Number value)
  {
    setAttributeInternal(IDPRIORITY, value);
  }

  /**Gets the attribute value for PRIORITY_CODE using the alias name PriorityCode
   */
  public String getPriorityCode()
  {
    return (String) getAttributeInternal(PRIORITYCODE);
  }

  /**Sets <code>value</code> as attribute value for PRIORITY_CODE using the alias name PriorityCode
   */
  public void setPriorityCode(String value)
  {
    setAttributeInternal(PRIORITYCODE, value);
  }

  /**Gets the attribute value for ACTIVATION_DATE using the alias name ActivationDate
   */
  public Date getActivationDate()
  {
    return (Date) getAttributeInternal(ACTIVATIONDATE);
  }

  /**Sets <code>value</code> as attribute value for ACTIVATION_DATE using the alias name ActivationDate
   */
  public void setActivationDate(Date value)
  {
    setAttributeInternal(ACTIVATIONDATE, value);
  }

  /**Gets the attribute value for ACTIVATION_TIME using the alias name ActivationTime
   */
  public String getActivationTime()
  {
    return (String) getAttributeInternal(ACTIVATIONTIME);
  }

  /**Sets <code>value</code> as attribute value for ACTIVATION_TIME using the alias name ActivationTime
   */
  public void setActivationTime(String value)
  {
    setAttributeInternal(ACTIVATIONTIME, value);
  }

  /**Gets the attribute value for MATERIAL_DATE using the alias name MaterialDate
   */
  public Date getMaterialDate()
  {
    return (Date) getAttributeInternal(MATERIALDATE);
  }

  /**Sets <code>value</code> as attribute value for MATERIAL_DATE using the alias name MaterialDate
   */
  public void setMaterialDate(Date value)
  {
    setAttributeInternal(MATERIALDATE, value);
  }

  /**Gets the attribute value for MATERIAL_TIME using the alias name MaterialTime
   */
  public String getMaterialTime()
  {
    return (String) getAttributeInternal(MATERIALTIME);
  }

  /**Sets <code>value</code> as attribute value for MATERIAL_TIME using the alias name MaterialTime
   */
  public void setMaterialTime(String value)
  {
    setAttributeInternal(MATERIALTIME, value);
  }

  /**Gets the attribute value for ID_SHIPPER using the alias name IdShipper
   */
  public Number getIdShipper()
  {
    return (Number) getAttributeInternal(IDSHIPPER);
  }

  /**Sets <code>value</code> as attribute value for ID_SHIPPER using the alias name IdShipper
   */
  public void setIdShipper(Number value)
  {
    setAttributeInternal(IDSHIPPER, value);
  }

  /**Gets the attribute value for SHIPPER using the alias name Shipper
   */
  public String getShipper()
  {
    return (String) getAttributeInternal(SHIPPER);
  }

  /**Sets <code>value</code> as attribute value for SHIPPER using the alias name Shipper
   */
  public void setShipper(String value)
  {
    setAttributeInternal(SHIPPER, value);
  }

  /**Gets the attribute value for ID_RECEIVER using the alias name IdReceiver
   */
  public Number getIdReceiver()
  {
    return (Number) getAttributeInternal(IDRECEIVER);
  }

  /**Sets <code>value</code> as attribute value for ID_RECEIVER using the alias name IdReceiver
   */
  public void setIdReceiver(Number value)
  {
    setAttributeInternal(IDRECEIVER, value);
  }

  /**Gets the attribute value for RECEIVER using the alias name Receiver
   */
  public String getReceiver()
  {
    return (String) getAttributeInternal(RECEIVER);
  }

  /**Sets <code>value</code> as attribute value for RECEIVER using the alias name Receiver
   */
  public void setReceiver(String value)
  {
    setAttributeInternal(RECEIVER, value);
  }

  /**Gets the attribute value for DOCUMENT1 using the alias name Document1
   */
  public String getDocument1()
  {
    return (String) getAttributeInternal(DOCUMENT1);
  }

  /**Sets <code>value</code> as attribute value for DOCUMENT1 using the alias name Document1
   */
  public void setDocument1(String value)
  {
    setAttributeInternal(DOCUMENT1, value);
  }

  /**Gets the attribute value for DOCUMENT2 using the alias name Document2
   */
  public String getDocument2()
  {
    return (String) getAttributeInternal(DOCUMENT2);
  }

  /**Sets <code>value</code> as attribute value for DOCUMENT2 using the alias name Document2
   */
  public void setDocument2(String value)
  {
    setAttributeInternal(DOCUMENT2, value);
  }

  /**Gets the attribute value for DOCUMENT3 using the alias name Document3
   */
  public String getDocument3()
  {
    return (String) getAttributeInternal(DOCUMENT3);
  }

  /**Sets <code>value</code> as attribute value for DOCUMENT3 using the alias name Document3
   */
  public void setDocument3(String value)
  {
    setAttributeInternal(DOCUMENT3, value);
  }

  /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
   */
  public String getAttribute1()
  {
    return (String) getAttributeInternal(ATTRIBUTE1);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
   */
  public String getAttribute2()
  {
    return (String) getAttributeInternal(ATTRIBUTE2);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
   */
  public String getAttribute3()
  {
    return (String) getAttributeInternal(ATTRIBUTE3);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
   */
  public String getAttribute4()
  {
    return (String) getAttributeInternal(ATTRIBUTE4);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
   */
  public String getAttribute5()
  {
    return (String) getAttributeInternal(ATTRIBUTE5);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
   */
  public String getAttribute6()
  {
    return (String) getAttributeInternal(ATTRIBUTE6);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
   */
  public void setAttribute6(String value)
  {
    setAttributeInternal(ATTRIBUTE6, value);
  }

  /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
   */
  public String getAttribute7()
  {
    return (String) getAttributeInternal(ATTRIBUTE7);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
   */
  public void setAttribute7(String value)
  {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
   */
  public String getAttribute8()
  {
    return (String) getAttributeInternal(ATTRIBUTE8);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
   */
  public void setAttribute8(String value)
  {
    setAttributeInternal(ATTRIBUTE8, value);
  }

  /**Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9
   */
  public String getAttribute9()
  {
    return (String) getAttributeInternal(ATTRIBUTE9);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9
   */
  public void setAttribute9(String value)
  {
    setAttributeInternal(ATTRIBUTE9, value);
  }

  /**Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10
   */
  public String getAttribute10()
  {
    return (String) getAttributeInternal(ATTRIBUTE10);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10
   */
  public void setAttribute10(String value)
  {
    setAttributeInternal(ATTRIBUTE10, value);
  }

  /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date) getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number) getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number) getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number) getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case IDREQUEST:
            return getIdRequest();
        case IDSTATUS:
            return getIdStatus();
        case STATUS:
            return getStatus();
        case OPERATINGUNIT:
            return getOperatingUnit();
        case OUDESCRIPTION:
            return getOuDescription();
        case IDAREA:
            return getIdArea();
        case ADESCRIPTION:
            return getADescription();
        case USERNAME:
            return getUserName();
        case IDPRIORITY:
            return getIdPriority();
        case PRIORITYCODE:
            return getPriorityCode();
        case ACTIVATIONDATE:
            return getActivationDate();
        case ACTIVATIONTIME:
            return getActivationTime();
        case MATERIALDATE:
            return getMaterialDate();
        case MATERIALTIME:
            return getMaterialTime();
        case IDSHIPPER:
            return getIdShipper();
        case SHIPPER:
            return getShipper();
        case IDRECEIVER:
            return getIdReceiver();
        case RECEIVER:
            return getReceiver();
        case DOCUMENT1:
            return getDocument1();
        case DOCUMENT2:
            return getDocument2();
        case DOCUMENT3:
            return getDocument3();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case COMMENTS:
            return getComments();
        case MULTIPLEDELIVERIES:
            return getMultipleDeliveries();
        case DESTINATION:
            return getDestination();
        case IDDESTINATION:
            return getIdDestination();
        case IDORIGIN:
            return getIdOrigin();
        case IDZONE:
            return getIdZone();
        case ORIGIN:
            return getOrigin();
        case ZONEDESC:
            return getZoneDesc();
        case FREIGHTENABLED:
            return getFreightEnabled();
        case ISRECORDENABLED:
            return getIsRecordEnabled();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case IDREQUEST:
            setIdRequest((Number)value);
            return;
        case IDSTATUS:
            setIdStatus((Number)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case OPERATINGUNIT:
            setOperatingUnit((String)value);
            return;
        case OUDESCRIPTION:
            setOuDescription((String)value);
            return;
        case IDAREA:
            setIdArea((Number)value);
            return;
        case ADESCRIPTION:
            setADescription((String)value);
            return;
        case USERNAME:
            setUserName((String)value);
            return;
        case IDPRIORITY:
            setIdPriority((Number)value);
            return;
        case PRIORITYCODE:
            setPriorityCode((String)value);
            return;
        case ACTIVATIONDATE:
            setActivationDate((Date)value);
            return;
        case ACTIVATIONTIME:
            setActivationTime((String)value);
            return;
        case MATERIALDATE:
            setMaterialDate((Date)value);
            return;
        case MATERIALTIME:
            setMaterialTime((String)value);
            return;
        case IDSHIPPER:
            setIdShipper((Number)value);
            return;
        case SHIPPER:
            setShipper((String)value);
            return;
        case IDRECEIVER:
            setIdReceiver((Number)value);
            return;
        case RECEIVER:
            setReceiver((String)value);
            return;
        case DOCUMENT1:
            setDocument1((String)value);
            return;
        case DOCUMENT2:
            setDocument2((String)value);
            return;
        case DOCUMENT3:
            setDocument3((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case COMMENTS:
            setComments((String)value);
            return;
        case MULTIPLEDELIVERIES:
            setMultipleDeliveries((String)value);
            return;
        case DESTINATION:
            setDestination((String)value);
            return;
        case IDDESTINATION:
            setIdDestination((Number)value);
            return;
        case IDORIGIN:
            setIdOrigin((Number)value);
            return;
        case IDZONE:
            setIdZone((Number)value);
            return;
        case ORIGIN:
            setOrigin((String)value);
            return;
        case ZONEDESC:
            setZoneDesc((String)value);
            return;
        case FREIGHTENABLED:
            setFreightEnabled((Boolean)value);
            return;
        case ISRECORDENABLED:
            setIsRecordEnabled((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

  /**Gets the attribute value for COMMENTS using the alias name Comments
   */
  public String getComments()
  {
    return (String) getAttributeInternal(COMMENTS);
  }

  /**Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments
   */
  public void setComments(String value)
  {
    setAttributeInternal(COMMENTS, value);
  }

  /**Gets the attribute value for MULTIPLE_DELIVERIES using the alias name MultipleDeliveries
   */
  public String getMultipleDeliveries()
  {
    return (String) getAttributeInternal(MULTIPLEDELIVERIES);
  }

  /**Sets <code>value</code> as attribute value for MULTIPLE_DELIVERIES using the alias name MultipleDeliveries
   */
  public void setMultipleDeliveries(String value)
  {
    setAttributeInternal(MULTIPLEDELIVERIES, value);
  }

  /**Gets the attribute value for DESTINATION using the alias name Destination
   */
  public String getDestination()
  {
    return (String) getAttributeInternal(DESTINATION);
  }

  /**Sets <code>value</code> as attribute value for DESTINATION using the alias name Destination
   */
  public void setDestination(String value)
  {
    setAttributeInternal(DESTINATION, value);
  }

  /**Gets the attribute value for ID_DESTINATION using the alias name IdDestination
   */
  public Number getIdDestination()
  {
    return (Number) getAttributeInternal(IDDESTINATION);
  }

  /**Sets <code>value</code> as attribute value for ID_DESTINATION using the alias name IdDestination
   */
  public void setIdDestination(Number value)
  {
    setAttributeInternal(IDDESTINATION, value);
  }

  /**Gets the attribute value for ID_ORIGIN using the alias name IdOrigin
   */
  public Number getIdOrigin()
  {
    return (Number) getAttributeInternal(IDORIGIN);
  }

  /**Sets <code>value</code> as attribute value for ID_ORIGIN using the alias name IdOrigin
   */
  public void setIdOrigin(Number value)
  {
    setAttributeInternal(IDORIGIN, value);
  }

  /**Gets the attribute value for ID_ZONE using the alias name IdZone
   */
  public Number getIdZone()
  {
    return (Number) getAttributeInternal(IDZONE);
  }

  /**Sets <code>value</code> as attribute value for ID_ZONE using the alias name IdZone
   */
  public void setIdZone(Number value)
  {
    setAttributeInternal(IDZONE, value);
  }

  /**Gets the attribute value for ORIGIN using the alias name Origin
   */
  public String getOrigin()
  {
    return (String) getAttributeInternal(ORIGIN);
  }

  /**Sets <code>value</code> as attribute value for ORIGIN using the alias name Origin
   */
  public void setOrigin(String value)
  {
    setAttributeInternal(ORIGIN, value);
  }

  /**Gets the attribute value for ZONE_DESC using the alias name ZoneDesc
   */
  public String getZoneDesc()
  {
    return (String) getAttributeInternal(ZONEDESC);
  }

  /**Sets <code>value</code> as attribute value for ZONE_DESC using the alias name ZoneDesc
   */
  public void setZoneDesc(String value)
  {
    setAttributeInternal(ZONEDESC, value);
  }

  /**Gets the attribute value for the calculated attribute FreightEnabled
   */
  public Boolean getFreightEnabled()
  {
    return (Boolean) getAttributeInternal(FREIGHTENABLED);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute FreightEnabled
   */
  public void setFreightEnabled(Boolean value)
  {
    setAttributeInternal(FREIGHTENABLED, value);
  }

  /**Gets the attribute value for the calculated attribute IsRecordEnabled
   */
  public Boolean getIsRecordEnabled()
  {
    return (Boolean) getAttributeInternal(ISRECORDENABLED);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute IsRecordEnabled
   */
  public void setIsRecordEnabled(Boolean value)
  {
    setAttributeInternal(ISRECORDENABLED, value);
  }


}
