package xxgam.oracle.apps.xbol.tm.poplist.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PoplistAMImpl extends OAApplicationModuleImpl
{
    /**This is the default constructor (do not remove)
     */
    public PoplistAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxgam.oracle.apps.xbol.tm.poplist.server", /* package name */
      "PoplistAMLocal" /* Configuration Name */);
    }

    /**Container's getter for TypeVO1
     */
    public TypeVOImpl getTypeVO1() {
        return (TypeVOImpl)findViewObject("TypeVO1");
    }

    /**Container's getter for HiretypeVO1
     */
    public HiretypeVOImpl getHiretypeVO1() {
        return (HiretypeVOImpl)findViewObject("HiretypeVO1");
    }

    /**Container's getter for CurrencyVO1
     */
    public CurrencyVOImpl getCurrencyVO1() {
        return (CurrencyVOImpl)findViewObject("CurrencyVO1");
    }

  /**Container's getter for RequestStatusVO1
   */
  public RequestStatusVOImpl getRequestStatusVO1()
  {
    return (RequestStatusVOImpl)findViewObject("RequestStatusVO1");
  }
}
