package xxgam.oracle.apps.xbol.tm.freight.schema;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestEOImpl extends OAEntityImpl
{
  public static final int IDREQUEST = 0;
  public static final int IDSTATUS = 1;
  public static final int STATUS = 2;
  public static final int OPERATINGUNIT = 3;
  public static final int OUDESCRIPTION = 4;
  public static final int IDAREA = 5;
  public static final int ADESCRIPTION = 6;
  public static final int USERNAME = 7;
  public static final int IDPRIORITY = 8;
  public static final int PRIORITYCODE = 9;
  public static final int ACTIVATIONDATE = 10;
  public static final int ACTIVATIONTIME = 11;
  public static final int MATERIALDATE = 12;
  public static final int MATERIALTIME = 13;
  public static final int IDSHIPPER = 14;
  public static final int SHIPPER = 15;
  public static final int IDRECEIVER = 16;
  public static final int RECEIVER = 17;
  public static final int DOCUMENT1 = 18;
  public static final int DOCUMENT2 = 19;
  public static final int DOCUMENT3 = 20;
  public static final int ATTRIBUTE1 = 21;
  public static final int ATTRIBUTE2 = 22;
  public static final int ATTRIBUTE3 = 23;
  public static final int ATTRIBUTE4 = 24;
  public static final int ATTRIBUTE5 = 25;
  public static final int ATTRIBUTE6 = 26;
  public static final int ATTRIBUTE7 = 27;
  public static final int ATTRIBUTE8 = 28;
  public static final int ATTRIBUTE9 = 29;
  public static final int ATTRIBUTE10 = 30;
  public static final int LASTUPDATEDATE = 31;
  public static final int LASTUPDATEDBY = 32;
  public static final int CREATIONDATE = 33;
  public static final int CREATEDBY = 34;
  public static final int LASTUPDATELOGIN = 35;
  public static final int COMMENTS = 36;
  public static final int MULTIPLEDELIVERIES = 37;
  public static final int DESTINATION = 38;
  public static final int IDDESTINATION = 39;
  public static final int IDORIGIN = 40;
  public static final int IDZONE = 41;
  public static final int ORIGIN = 42;
  public static final int ZONEDESC = 43;


  private static OAEntityDefImpl mDefinitionObject;

  /**This is the default constructor (do not remove)
   */
  public RequestEOImpl()
  {
  }


  /**Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = 
          (OAEntityDefImpl)EntityDefImpl.findDefObject("xxgam.oracle.apps.xbol.tm.freight.schema.RequestEO");
    }
    return mDefinitionObject;
  }

  /**Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList)
  {
    super.create(attributeList);
  }

  /**Add entity remove logic in this method.
   */
  public void remove()
  {
    super.remove();
  }

  /**Add Entity validation code in this method.
   */
  protected void validateEntity()
  {
    super.validateEntity();
  }

  /**Gets the attribute value for IdRequest, using the alias name IdRequest
   */
  public Number getIdRequest()
  {
    return (Number)getAttributeInternal(IDREQUEST);
  }

  /**Sets <code>value</code> as the attribute value for IdRequest
   */
  public void setIdRequest(Number value)
  {
    setAttributeInternal(IDREQUEST, value);
  }

  /**Gets the attribute value for IdStatus, using the alias name IdStatus
   */
  public Number getIdStatus()
  {
    return (Number)getAttributeInternal(IDSTATUS);
  }

  /**Sets <code>value</code> as the attribute value for IdStatus
   */
  public void setIdStatus(Number value)
  {
    setAttributeInternal(IDSTATUS, value);
  }

  /**Gets the attribute value for Status, using the alias name Status
   */
  public String getStatus()
  {
    return (String)getAttributeInternal(STATUS);
  }

  /**Sets <code>value</code> as the attribute value for Status
   */
  public void setStatus(String value)
  {
    setAttributeInternal(STATUS, value);
  }

  /**Gets the attribute value for OperatingUnit, using the alias name OperatingUnit
   */
  public String getOperatingUnit()
  {
    return (String)getAttributeInternal(OPERATINGUNIT);
  }

  /**Sets <code>value</code> as the attribute value for OperatingUnit
   */
  public void setOperatingUnit(String value)
  {
    setAttributeInternal(OPERATINGUNIT, value);
  }

  /**Gets the attribute value for OuDescription, using the alias name OuDescription
   */
  public String getOuDescription()
  {
    return (String)getAttributeInternal(OUDESCRIPTION);
  }

  /**Sets <code>value</code> as the attribute value for OuDescription
   */
  public void setOuDescription(String value)
  {
    setAttributeInternal(OUDESCRIPTION, value);
  }

  /**Gets the attribute value for IdArea, using the alias name IdArea
   */
  public Number getIdArea()
  {
    return (Number)getAttributeInternal(IDAREA);
  }

  /**Sets <code>value</code> as the attribute value for IdArea
   */
  public void setIdArea(Number value)
  {
    setAttributeInternal(IDAREA, value);
  }

  /**Gets the attribute value for ADescription, using the alias name ADescription
   */
  public String getADescription()
  {
    return (String)getAttributeInternal(ADESCRIPTION);
  }

  /**Sets <code>value</code> as the attribute value for ADescription
   */
  public void setADescription(String value)
  {
    setAttributeInternal(ADESCRIPTION, value);
  }

  /**Gets the attribute value for UserName, using the alias name UserName
   */
  public String getUserName()
  {
    return (String)getAttributeInternal(USERNAME);
  }

  /**Sets <code>value</code> as the attribute value for UserName
   */
  public void setUserName(String value)
  {
    setAttributeInternal(USERNAME, value);
  }

  /**Gets the attribute value for IdPriority, using the alias name IdPriority
   */
  public Number getIdPriority()
  {
    return (Number)getAttributeInternal(IDPRIORITY);
  }

  /**Sets <code>value</code> as the attribute value for IdPriority
   */
  public void setIdPriority(Number value)
  {
    setAttributeInternal(IDPRIORITY, value);
  }

  /**Gets the attribute value for PriorityCode, using the alias name PriorityCode
   */
  public String getPriorityCode()
  {
    return (String)getAttributeInternal(PRIORITYCODE);
  }

  /**Sets <code>value</code> as the attribute value for PriorityCode
   */
  public void setPriorityCode(String value)
  {
    setAttributeInternal(PRIORITYCODE, value);
  }

  /**Gets the attribute value for ActivationDate, using the alias name ActivationDate
   */
  public Date getActivationDate()
  {
    return (Date)getAttributeInternal(ACTIVATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for ActivationDate
   */
  public void setActivationDate(Date value)
  {
    setAttributeInternal(ACTIVATIONDATE, value);
  }

  /**Gets the attribute value for ActivationTime, using the alias name ActivationTime
   */
  public String getActivationTime()
  {
    return (String)getAttributeInternal(ACTIVATIONTIME);
  }

  /**Sets <code>value</code> as the attribute value for ActivationTime
   */
  public void setActivationTime(String value)
  {
    setAttributeInternal(ACTIVATIONTIME, value);
  }

  /**Gets the attribute value for MaterialDate, using the alias name MaterialDate
   */
  public Date getMaterialDate()
  {
    return (Date)getAttributeInternal(MATERIALDATE);
  }

  /**Sets <code>value</code> as the attribute value for MaterialDate
   */
  public void setMaterialDate(Date value)
  {
    setAttributeInternal(MATERIALDATE, value);
  }

  /**Gets the attribute value for MaterialTime, using the alias name MaterialTime
   */
  public String getMaterialTime()
  {
    return (String)getAttributeInternal(MATERIALTIME);
  }

  /**Sets <code>value</code> as the attribute value for MaterialTime
   */
  public void setMaterialTime(String value)
  {
    setAttributeInternal(MATERIALTIME, value);
  }

  /**Gets the attribute value for IdShipper, using the alias name IdShipper
   */
  public Number getIdShipper()
  {
    return (Number)getAttributeInternal(IDSHIPPER);
  }

  /**Sets <code>value</code> as the attribute value for IdShipper
   */
  public void setIdShipper(Number value)
  {
    setAttributeInternal(IDSHIPPER, value);
  }

  /**Gets the attribute value for Shipper, using the alias name Shipper
   */
  public String getShipper()
  {
    return (String)getAttributeInternal(SHIPPER);
  }

  /**Sets <code>value</code> as the attribute value for Shipper
   */
  public void setShipper(String value)
  {
    setAttributeInternal(SHIPPER, value);
  }

  /**Gets the attribute value for IdReceiver, using the alias name IdReceiver
   */
  public Number getIdReceiver()
  {
    return (Number)getAttributeInternal(IDRECEIVER);
  }

  /**Sets <code>value</code> as the attribute value for IdReceiver
   */
  public void setIdReceiver(Number value)
  {
    setAttributeInternal(IDRECEIVER, value);
  }

  /**Gets the attribute value for Receiver, using the alias name Receiver
   */
  public String getReceiver()
  {
    return (String)getAttributeInternal(RECEIVER);
  }

  /**Sets <code>value</code> as the attribute value for Receiver
   */
  public void setReceiver(String value)
  {
    setAttributeInternal(RECEIVER, value);
  }

  /**Gets the attribute value for Document1, using the alias name Document1
   */
  public String getDocument1()
  {
    return (String)getAttributeInternal(DOCUMENT1);
  }

  /**Sets <code>value</code> as the attribute value for Document1
   */
  public void setDocument1(String value)
  {
    setAttributeInternal(DOCUMENT1, value);
  }

  /**Gets the attribute value for Document2, using the alias name Document2
   */
  public String getDocument2()
  {
    return (String)getAttributeInternal(DOCUMENT2);
  }

  /**Sets <code>value</code> as the attribute value for Document2
   */
  public void setDocument2(String value)
  {
    setAttributeInternal(DOCUMENT2, value);
  }

  /**Gets the attribute value for Document3, using the alias name Document3
   */
  public String getDocument3()
  {
    return (String)getAttributeInternal(DOCUMENT3);
  }

  /**Sets <code>value</code> as the attribute value for Document3
   */
  public void setDocument3(String value)
  {
    setAttributeInternal(DOCUMENT3, value);
  }

  /**Gets the attribute value for Attribute1, using the alias name Attribute1
   */
  public String getAttribute1()
  {
    return (String)getAttributeInternal(ATTRIBUTE1);
  }

  /**Sets <code>value</code> as the attribute value for Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**Gets the attribute value for Attribute2, using the alias name Attribute2
   */
  public String getAttribute2()
  {
    return (String)getAttributeInternal(ATTRIBUTE2);
  }

  /**Sets <code>value</code> as the attribute value for Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**Gets the attribute value for Attribute3, using the alias name Attribute3
   */
  public String getAttribute3()
  {
    return (String)getAttributeInternal(ATTRIBUTE3);
  }

  /**Sets <code>value</code> as the attribute value for Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**Gets the attribute value for Attribute4, using the alias name Attribute4
   */
  public String getAttribute4()
  {
    return (String)getAttributeInternal(ATTRIBUTE4);
  }

  /**Sets <code>value</code> as the attribute value for Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**Gets the attribute value for Attribute5, using the alias name Attribute5
   */
  public String getAttribute5()
  {
    return (String)getAttributeInternal(ATTRIBUTE5);
  }

  /**Sets <code>value</code> as the attribute value for Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**Gets the attribute value for Attribute6, using the alias name Attribute6
   */
  public String getAttribute6()
  {
    return (String)getAttributeInternal(ATTRIBUTE6);
  }

  /**Sets <code>value</code> as the attribute value for Attribute6
   */
  public void setAttribute6(String value)
  {
    setAttributeInternal(ATTRIBUTE6, value);
  }

  /**Gets the attribute value for Attribute7, using the alias name Attribute7
   */
  public String getAttribute7()
  {
    return (String)getAttributeInternal(ATTRIBUTE7);
  }

  /**Sets <code>value</code> as the attribute value for Attribute7
   */
  public void setAttribute7(String value)
  {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**Gets the attribute value for Attribute8, using the alias name Attribute8
   */
  public String getAttribute8()
  {
    return (String)getAttributeInternal(ATTRIBUTE8);
  }

  /**Sets <code>value</code> as the attribute value for Attribute8
   */
  public void setAttribute8(String value)
  {
    setAttributeInternal(ATTRIBUTE8, value);
  }

  /**Gets the attribute value for Attribute9, using the alias name Attribute9
   */
  public String getAttribute9()
  {
    return (String)getAttributeInternal(ATTRIBUTE9);
  }

  /**Sets <code>value</code> as the attribute value for Attribute9
   */
  public void setAttribute9(String value)
  {
    setAttributeInternal(ATTRIBUTE9, value);
  }

  /**Gets the attribute value for Attribute10, using the alias name Attribute10
   */
  public String getAttribute10()
  {
    return (String)getAttributeInternal(ATTRIBUTE10);
  }

  /**Sets <code>value</code> as the attribute value for Attribute10
   */
  public void setAttribute10(String value)
  {
    setAttributeInternal(ATTRIBUTE10, value);
  }

  /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case IDREQUEST:
      return getIdRequest();
    case IDSTATUS:
      return getIdStatus();
    case STATUS:
      return getStatus();
    case OPERATINGUNIT:
      return getOperatingUnit();
    case OUDESCRIPTION:
      return getOuDescription();
    case IDAREA:
      return getIdArea();
    case ADESCRIPTION:
      return getADescription();
    case USERNAME:
      return getUserName();
    case IDPRIORITY:
      return getIdPriority();
    case PRIORITYCODE:
      return getPriorityCode();
    case ACTIVATIONDATE:
      return getActivationDate();
    case ACTIVATIONTIME:
      return getActivationTime();
    case MATERIALDATE:
      return getMaterialDate();
    case MATERIALTIME:
      return getMaterialTime();
    case IDSHIPPER:
      return getIdShipper();
    case SHIPPER:
      return getShipper();
    case IDRECEIVER:
      return getIdReceiver();
    case RECEIVER:
      return getReceiver();
    case DOCUMENT1:
      return getDocument1();
    case DOCUMENT2:
      return getDocument2();
    case DOCUMENT3:
      return getDocument3();
    case ATTRIBUTE1:
      return getAttribute1();
    case ATTRIBUTE2:
      return getAttribute2();
    case ATTRIBUTE3:
      return getAttribute3();
    case ATTRIBUTE4:
      return getAttribute4();
    case ATTRIBUTE5:
      return getAttribute5();
    case ATTRIBUTE6:
      return getAttribute6();
    case ATTRIBUTE7:
      return getAttribute7();
    case ATTRIBUTE8:
      return getAttribute8();
    case ATTRIBUTE9:
      return getAttribute9();
    case ATTRIBUTE10:
      return getAttribute10();
    case LASTUPDATEDATE:
      return getLastUpdateDate();
    case LASTUPDATEDBY:
      return getLastUpdatedBy();
    case CREATIONDATE:
      return getCreationDate();
    case CREATEDBY:
      return getCreatedBy();
    case LASTUPDATELOGIN:
      return getLastUpdateLogin();
    case COMMENTS:
      return getComments();
    case MULTIPLEDELIVERIES:
      return getMultipleDeliveries();
    case DESTINATION:
      return getDestination();
    case IDDESTINATION:
      return getIdDestination();
    case IDORIGIN:
      return getIdOrigin();
    case IDZONE:
      return getIdZone();
    case ORIGIN:
      return getOrigin();
    case ZONEDESC:
      return getZoneDesc();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case IDREQUEST:
      setIdRequest((Number)value);
      return;
    case IDSTATUS:
      setIdStatus((Number)value);
      return;
    case STATUS:
      setStatus((String)value);
      return;
    case OPERATINGUNIT:
      setOperatingUnit((String)value);
      return;
    case OUDESCRIPTION:
      setOuDescription((String)value);
      return;
    case IDAREA:
      setIdArea((Number)value);
      return;
    case ADESCRIPTION:
      setADescription((String)value);
      return;
    case USERNAME:
      setUserName((String)value);
      return;
    case IDPRIORITY:
      setIdPriority((Number)value);
      return;
    case PRIORITYCODE:
      setPriorityCode((String)value);
      return;
    case ACTIVATIONDATE:
      setActivationDate((Date)value);
      return;
    case ACTIVATIONTIME:
      setActivationTime((String)value);
      return;
    case MATERIALDATE:
      setMaterialDate((Date)value);
      return;
    case MATERIALTIME:
      setMaterialTime((String)value);
      return;
    case IDSHIPPER:
      setIdShipper((Number)value);
      return;
    case SHIPPER:
      setShipper((String)value);
      return;
    case IDRECEIVER:
      setIdReceiver((Number)value);
      return;
    case RECEIVER:
      setReceiver((String)value);
      return;
    case DOCUMENT1:
      setDocument1((String)value);
      return;
    case DOCUMENT2:
      setDocument2((String)value);
      return;
    case DOCUMENT3:
      setDocument3((String)value);
      return;
    case ATTRIBUTE1:
      setAttribute1((String)value);
      return;
    case ATTRIBUTE2:
      setAttribute2((String)value);
      return;
    case ATTRIBUTE3:
      setAttribute3((String)value);
      return;
    case ATTRIBUTE4:
      setAttribute4((String)value);
      return;
    case ATTRIBUTE5:
      setAttribute5((String)value);
      return;
    case ATTRIBUTE6:
      setAttribute6((String)value);
      return;
    case ATTRIBUTE7:
      setAttribute7((String)value);
      return;
    case ATTRIBUTE8:
      setAttribute8((String)value);
      return;
    case ATTRIBUTE9:
      setAttribute9((String)value);
      return;
    case ATTRIBUTE10:
      setAttribute10((String)value);
      return;
    case LASTUPDATEDATE:
      setLastUpdateDate((Date)value);
      return;
    case LASTUPDATEDBY:
      setLastUpdatedBy((Number)value);
      return;
    case CREATIONDATE:
      setCreationDate((Date)value);
      return;
    case CREATEDBY:
      setCreatedBy((Number)value);
      return;
    case LASTUPDATELOGIN:
      setLastUpdateLogin((Number)value);
      return;
    case COMMENTS:
      setComments((String)value);
      return;
    case MULTIPLEDELIVERIES:
      setMultipleDeliveries((String)value);
      return;
    case DESTINATION:
      setDestination((String)value);
      return;
    case IDDESTINATION:
      setIdDestination((Number)value);
      return;
    case IDORIGIN:
      setIdOrigin((Number)value);
      return;
    case IDZONE:
      setIdZone((Number)value);
      return;
    case ORIGIN:
      setOrigin((String)value);
      return;
    case ZONEDESC:
      setZoneDesc((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the attribute value for Comments, using the alias name Comments
   */
  public String getComments()
  {
    return (String)getAttributeInternal(COMMENTS);
  }

  /**Sets <code>value</code> as the attribute value for Comments
   */
  public void setComments(String value)
  {
    setAttributeInternal(COMMENTS, value);
  }

  /**Gets the attribute value for MultipleDeliveries, using the alias name MultipleDeliveries
   */
  public String getMultipleDeliveries()
  {
    return (String)getAttributeInternal(MULTIPLEDELIVERIES);
  }

  /**Sets <code>value</code> as the attribute value for MultipleDeliveries
   */
  public void setMultipleDeliveries(String value)
  {
    setAttributeInternal(MULTIPLEDELIVERIES, value);
  }

  /**Gets the attribute value for Destination, using the alias name Destination
   */
  public String getDestination()
  {
    return (String)getAttributeInternal(DESTINATION);
  }

  /**Sets <code>value</code> as the attribute value for Destination
   */
  public void setDestination(String value)
  {
    setAttributeInternal(DESTINATION, value);
  }

  /**Gets the attribute value for IdDestination, using the alias name IdDestination
   */
  public Number getIdDestination()
  {
    return (Number)getAttributeInternal(IDDESTINATION);
  }

  /**Sets <code>value</code> as the attribute value for IdDestination
   */
  public void setIdDestination(Number value)
  {
    setAttributeInternal(IDDESTINATION, value);
  }

  /**Gets the attribute value for IdOrigin, using the alias name IdOrigin
   */
  public Number getIdOrigin()
  {
    return (Number)getAttributeInternal(IDORIGIN);
  }

  /**Sets <code>value</code> as the attribute value for IdOrigin
   */
  public void setIdOrigin(Number value)
  {
    setAttributeInternal(IDORIGIN, value);
  }

  /**Gets the attribute value for IdZone, using the alias name IdZone
   */
  public Number getIdZone()
  {
    return (Number)getAttributeInternal(IDZONE);
  }

  /**Sets <code>value</code> as the attribute value for IdZone
   */
  public void setIdZone(Number value)
  {
    setAttributeInternal(IDZONE, value);
  }

  /**Gets the attribute value for Origin, using the alias name Origin
   */
  public String getOrigin()
  {
    return (String)getAttributeInternal(ORIGIN);
  }

  /**Sets <code>value</code> as the attribute value for Origin
   */
  public void setOrigin(String value)
  {
    setAttributeInternal(ORIGIN, value);
  }

  /**Gets the attribute value for ZoneDesc, using the alias name ZoneDesc
   */
  public String getZoneDesc()
  {
    return (String)getAttributeInternal(ZONEDESC);
  }

  /**Sets <code>value</code> as the attribute value for ZoneDesc
   */
  public void setZoneDesc(String value)
  {
    setAttributeInternal(ZONEDESC, value);
  }

  /**Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idRequest)
  {
    return new Key(new Object[]{idRequest});
  }
}
