package xxgam.oracle.apps.xbol.tm.poplist.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HiretypeVORowImpl extends OAViewRowImpl {
    public static final int TIPO = 0;

    /**This is the default constructor (do not remove)
     */
    public HiretypeVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Tipo
     */
    public String getTipo() {
        return (String) getAttributeInternal(TIPO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tipo
     */
    public void setTipo(String value) {
        setAttributeInternal(TIPO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TIPO:
            return getTipo();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
